<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InitConfig extends Seeder
{
    public function run()
    {
        $configdata = array(
            'site_title' => '홈페이지',
            'site_logo' => '홈페이지',
            'admin_logo' => 'Admin',
            'webmaster_name' => '관리자',
            'webmaster_email' => 'noreply@domain.com',
            'new_post_second' => '30',
            'open_currentvisitor' => '1',
            'currentvisitor_minute' => '10',
            'use_copy_log' => '1',
            'max_level' => '100',
            'ip_display_style' => '1001',
            'list_count' => '20',
            'site_blacklist_title' => '사이트가 공사중에 있습니다',
            'site_blacklist_content' => '<p>안녕하세요</p><p>블편을 드려 죄송합니다. 지금 이 사이트는 접근이 금지되어있습니다</p><p>감사합니다</p>',
            'use_point' => '1',
            'point_register' => '50',
            'point_login' => '5',
            'point_recommended' => '5',
            'point_recommender' => '5',
            'point_note' => '10',
            'block_download_zeropoint' => '1',
            'block_read_zeropoint' => '1',
            'use_sideview' => '1',
            'use_mobile_sideview' => '1',
            'use_sideview_email' => '1',
            'use_mobile_sideview_email' => '1',
            'post_editor_type' => 'smarteditor',
            'use_document_dhtml' => '1',
            'document_editor_type' => 'smarteditor',
            'document_thumb_width' => '700',
            'document_mobile_thumb_width' => '400',
            'document_content_target_blank' => '1',
            'use_document_auto_url' => '1',
            'use_faq_dhtml' => '1',
            'faq_editor_type' => 'smarteditor',
            'faq_thumb_width' => '700',
            'faq_mobile_thumb_width' => '400',
            'faq_content_target_blank' => '1',
            'use_faq_auto_url' => '1',
            'use_popup_dhtml' => '1',
            'popup_editor_type' => 'smarteditor',
            'popup_thumb_width' => '700',
            'popup_mobile_thumb_width' => '400',
            'popup_content_target_blank' => '1',
            'use_popup_auto_url' => '1',
            'use_formmail_dhtml' => '1',
            'formmail_editor_type' => 'smarteditor',
            'use_note' => '1',
            'note_list_page' => '10',
            'note_mobile_list_page' => '10',
            'use_note_dhtml' => '1',
            'use_note_mobile_dhtml' => '1',
            'note_editor_type' => 'smarteditor',
            'use_notification' => '1',
            'notification_reply' => '1',
            'notification_comment' => '1',
            'notification_comment_comment' => '1',
            'notification_note' => '1',
            'password_length' => '4',
            'use_member_photo' => '1',
            'member_photo_width' => '80',
            'member_photo_height' => '80',
            'use_member_icon' => '1',
            'member_icon_width' => '20',
            'member_icon_height' => '20',
            'denied_nickname_list' => 'admin,administrator,관리자,운영자,어드민,주인장,webmaster,웹마스터,sysop,시삽,시샵,manager,매니저,메니저,root,루트,su,guest,방문객',
            'denied_userid_list' => 'admin,administrator,webmaster,sysop,manager,root,su,guest,super',
            'member_register_policy1' => '회원약관을 입력해주세요',
            'member_register_policy2' => '개인정보취급방침을 입력해주세요',
            'register_level' => '1',
            'change_nickname_date' => '60',
            'change_open_profile_date' => '60',
            'change_use_note_date' => '60',
            'change_password_date' => '180',
            'max_login_try_count' => '5',
            'max_login_try_limit_second' => '30',
            'total_rss_feed_count' => '100',
        );
        $registerform = array(
            'mem_userid' => array(
                'field_name' => 'mem_userid',
                'func' => 'basic',
                'display_name' => '아이디',
                'field_type' => 'text',
                'use' => '1',
                'open' => '1',
                'required' => '1',
            ),
            'mem_email' => array(
                'field_name' => 'mem_email',
                'func' => 'basic',
                'display_name' => '이메일주소',
                'field_type' => 'email',
                'use' => '1',
                'open' => '',
                'required' => '1',
            ),
            'mem_password' => array(
                'field_name' => 'mem_password',
                'func' => 'basic',
                'display_name' => '비밀번호',
                'field_type' => 'password',
                'use' => '1',
                'open' => '',
                'required' => '1',
            ),
            'mem_username' => array(
                'field_name' => 'mem_username',
                'func' => 'basic',
                'display_name' => '이름',
                'field_type' => 'text',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
            'mem_nickname' => array(
                'field_name' => 'mem_nickname',
                'func' => 'basic',
                'display_name' => '닉네임',
                'field_type' => 'text',
                'use' => '1',
                'open' => '1',
                'required' => '1',
            ),
            'mem_homepage' => array(
                'field_name' => 'mem_homepage',
                'func' => 'basic',
                'display_name' => '홈페이지',
                'field_type' => 'url',
                'use' => '',
                'open' => '1',
                'required' => '',
            ),
            'mem_phone' => array(
                'field_name' => 'mem_phone',
                'func' => 'basic',
                'display_name' => '전화번호',
                'field_type' => 'phone',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
            'mem_birthday' => array(
                'field_name' => 'mem_birthday',
                'func' => 'basic',
                'display_name' => '생년월일',
                'field_type' => 'date',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
            'mem_sex' => array(
                'field_name' => 'mem_sex',
                'func' => 'basic',
                'display_name' => '성별',
                'field_type' => 'radio',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
            'mem_address' => array(
                'field_name' => 'mem_address',
                'func' => 'basic',
                'display_name' => '주소',
                'field_type' => 'address',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
            'mem_profile_content' => array(
                'field_name' => 'mem_profile_content',
                'func' => 'basic',
                'display_name' => '자기소개',
                'field_type' => 'textarea',
                'use' => '',
                'open' => '1',
                'required' => '',
            ),
            'mem_recommend' => array(
                'field_name' => 'mem_recommend',
                'func' => 'basic',
                'display_name' => '추천인',
                'field_type' => 'text',
                'use' => '',
                'open' => '',
                'required' => '',
            ),
        );
        $configdata['registerform'] = json_encode($registerform);
        $this->db->table('config')->truncate();
        foreach ($configdata as $column => $value) {
            $updatedata[] = array(
                'cfg_key' => $column,
                'cfg_value' => $value,
            );
        }
        $this->db->table('config')->insertBatch($updatedata);
    }
}
